FEATURE: Implement component for displaying Favicons in frontend
neos/Neos.Demo pull request #176
Opened 2023-07-20 18:53 UTC by crydotsnake

2023-07-20 19:02 UTC, mhsdesign commented
Thanks for your work ^^ Is it normal that this seems so complex / verbose?

I mean this is supposed to be a exemplary demo - im not sure if this wouldnt scare people away :P 

... But if this is the way. I would not oppose.

<img width="127" alt="image" src="https://github.com/neos/Neos.Demo/assets/85400359/78d9cd5e-5eb2-4054-9bb8-31d755018d74">

2023-07-20 19:19 UTC, crydotsnake commented
Well. You could also use a fluid file with the HTML for the favicons. And a fusion file that inherits from `Neos.Fusion:Template` and just has the `package` and the Fluid file as the `templatePath` as propertys.

But the idea as I have solved it here came to me as the first thought.

2023-07-20 19:26 UTC, Sebobo requested changes
Today you don't need so many icons anymore, see https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs or other articles. Also the manifest should be adjustable or have safe placeholders, as it contains something about Sandstorm and Neos and people might just copy it. 
To make the manifest adjustable, similar to the Robots.txt in Neos.Seo would actually be a cool example I think. Also I would not use the ResourceUri but directly use the StaticResource Eelhelper in the Tag. They should anyway be a bit more individual and not all have the 32px size attribute.

2023-07-20 19:29 UTC, crydotsnake commented
> Today you don't need so many icons anymore, see https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs or other articles.

First i thought about using a favicon generator. For example: https://realfavicongenerator.net/

But was not sure if this would be a good solution. Wdyt?

2023-07-21 07:03 UTC, Sebobo commented
Why not just remove the tags you don't need and keep the rest and just do a few adjustments?
Don't fully understand your question regarding the generator and how it would help?

2024-09-16 11:14 UTC, Sebobo approved these changes

2024-09-16 11:14 UTC, Sebobo commented
Should target 8.4 though

2024-09-16 12:54 UTC, crydotsnake commented
> Should target 8.4 though

Done.

2025-06-23 14:27 UTC, Sebobo commented on Resources/Private/Fusion/Presentation/Favicons.fusion
> +        <link rel="apple-touch-icon" sizes="180x180" href={StaticResource.uri('Neos.Demo', 'Public/Assets/Favicons/apple-touch-icon.png')} />
If you make the `packageName` a prop, then this component could be easily copied to custom projects and reused, as only the package name needs to be overridden and the files copied to the proper spot.

2025-06-24 12:18 UTC, Sebobo approved these changes
LGTM, thx

2025-06-24 12:27 UTC, markusguenther reviewed
Thanks @crydotsnake for this change. Is there a reason for having a different logo variant in the size 70x70?

2025-06-24 12:31 UTC, crydotsnake commented
> Thanks @crydotsnake for this change. Is there a reason for having a different logo variant in the size 70x70?

I used a favicon generate which maybe was not the best idea 🤔 I believe this alternative is for dark modes for microsoft edge. But i'm not 100% sure. I used https://realfavicongenerator.net/ i belive..

2025-06-24 12:42 UTC, markusguenther commented
Hmm, in the end, we don’t need that many-sized PNG files.
We can use one SVG for the modern browsers and could also use the CSS query for dark mode with that if we want. But as the demo is not using dark mode stuff at all, we don’t need it either.
https://blog.tomayac.com/2021/07/21/dark-mode-web-app-manifest-app-icons/

So my suggestion would be to add one SVG and a PNG as a fallback for the devices that do not use it yet.
WDYT?

2025-06-24 12:46 UTC, crydotsnake commented
> Hmm, in the end, we don’t need that many-sized PNG files. We can use one SVG for the modern browsers and could also use the CSS query for dark mode with that if we want. But as the demo is not using dark mode stuff at all, we don’t need it either. https://blog.tomayac.com/2021/07/21/dark-mode-web-app-manifest-app-icons/
> 
> So my suggestion would be to add one SVG and a PNG as a fallback for the devices that do not use it yet. WDYT?

Sounds fine to me. Which site would you use to create the favicon png and svg variant?

2025-06-24 12:46 UTC, markusguenther commented
Ok maybe ico as fallback as windows is an issue ;)

> ICO: Universally supported across all browsers and platforms, including very old ones.
> PNG: Supported by most modern browsers, but not all platforms (e.g., Windows taskbar prefers .ico).

2025-06-24 12:48 UTC, markusguenther commented
We have all SVG icons and just need to use the ico then, but bet we already have a ico file in the project.
https://github.com/neos/brand/tree/master/logos/Neos

2025-06-24 12:50 UTC, markusguenther commented
Here you have already an ICO Resources/Public/Assets/Favicons/favicon.ico

2025-06-24 13:41 UTC, crydotsnake commented
@markusguenther Can you take a look again?

2025-06-24 15:39 UTC, jonnitto requested changes
It would be better if the favicon has an aspect ratio of 1:1

2025-06-24 16:38 UTC, markusguenther commented
Would have chnaged it, but was not allowed to push.

2025-06-24 19:55 UTC, crydotsnake commented
> Would have chnaged it, but was not allowed to push.

Maybe because of my fork. If you want, I can invite you to my fork repo.

2025-10-10 06:49 UTC, crydotsnake commented
> > Would have chnaged it, but was not allowed to push.
> 
> Maybe because of my fork. If you want, I can invite you to my fork repo.

@markusguenther ping ;)

2026-05-09 12:42 UTC, crydotsnake commented
@markusguenther @Sebobo @jonnitto Is there anything I need to do so we can merge this ? :)

2026-07-21 20:04 UTC, closed without merging