FEATURE: Improve visual feedback of Blog Cards
neos/Neos.Demo pull request #177
Opened 2023-07-22 10:41 UTC by crydotsnake

This pull request improves the visual feedback of the cards by showing the publishing date of a blog post, and the name of the author who wrote the blog post.

![SCR-20230722-lirl](https://github.com/neos/Neos.Demo/assets/39345336/1b5ecd6e-5bf5-4580-9892-9dedbdb3f8f9)

2023-07-24 08:11 UTC, jonnitto requested changes

2023-07-24 08:11 UTC, jonnitto commented on Resources/Private/Fusion/Presentation/Cards/Card.fusion
> +                    {I18n.translate('Neos.Demo:Presentation.Cards:cards.authorPublishedBy') + props.authorName}
I would prefer to pass the author name as variable into the translation helper.

2023-07-24 08:11 UTC, jonnitto commented on Resources/Private/Fusion/Presentation/Cards/Card.fusion
> +                <p class="pb-3 italic text-sm">
```suggestion
                <p class="pb-3 italic text-sm" @if={props.authorName} >
```

2023-07-24 08:11 UTC, jonnitto commented on Resources/Private/Fusion/Presentation/Cards/Card.fusion
> +                </p>
Use `time` tag and write the date in a long format

```suggestion
                <time datetime={Date.format(props.date, 'Y-m-d')} @if={props.date}>
                    {Date.formatCldr(props.date, 'd. MMMM y')}
                </time>
```

2023-07-24 08:11 UTC, jonnitto commented on NodeTypes/Document/Blog/Blog.fusion
> +                    date = ${Date.format(q(blogPosting).property('datePublished'), 'M. Y-m-d')}
How to write the date is part of presentation
```suggestion
                    date = ${q(blogPosting).property('datePublished')}
```

2023-07-24 08:11 UTC, jonnitto commented on NodeTypes/Content/BlogPostingList/BlogPostingList.fusion
> +                date = ${Date.format(q(blogPosting).property('datePublished'), 'M. Y-m-d')}
How to write the date is part of presentation

```suggestion
                date = ${q(blogPosting).property('datePublished')}
```

2023-07-25 22:01 UTC, jonnitto approved these changes

2023-07-27 08:08 UTC, Sebobo approved these changes
Looks good by reading, thx!

2023-07-30 06:18 UTC, merged