BUGFIX: allow YoutubeCarousel element only in the Carousel Content Element
neos/Neos.Demo pull request #181
Opened 2023-09-04 18:42 UTC by crydotsnake

resolves: #180 

It should not be possible to use the Youtube Content Element for the Carousel Slider on the hole page.

2023-09-04 20:23 UTC, mhsdesign commented on NodeTypes/Collection/Content/Main.yaml
> +      'Neos.Demo:Content.CarouselYouTube': false
hmm we are using this pattern here to have the `Neos.Demo:Constraint.Content.Main` be a mixin - so as long as the `Neos.Demo:Content.CarouselYouTube` doesnt extend this mixin - it should be fine

see https://docs.neos.io/tutorials/better-constraints

2023-09-11 08:37 UTC, Sebobo requested changes
Please introduce and use a constraint type here

2023-11-12 15:43 UTC, crydotsnake commented
> Please introduce and use a constraint type here

There was already a constraint for the carousel. So i used that :)

2024-01-01 21:02 UTC, merged

2024-12-13 16:42 UTC, mhsdesign commented
This change introduced a regression, that no simple text nodes f.x.  could be added: https://github.com/neos/Neos.Demo/pull/201