BUGFIX: Remove plow-js from code tag plugin
neos/Neos.Demo pull request #184
Opened 2023-10-16 21:22 UTC by mhsdesign

This way we get rid of the console errors:

> Warning: Plow.js "$get" is deprecated! See: https://github.com/neos/neos-ui/issues/3425

2023-10-16 21:24 UTC, mhsdesign commented
The plugin seems to work still after testing:

<img width="578" alt="image" src="https://github.com/neos/Neos.Demo/assets/85400359/3c6e1780-5c0a-4694-ac88-e7818dbf0c5a">

2023-10-16 21:25 UTC, mhsdesign commented
And we must upmerge/cherry-pick this to 9.0 as well ;)

2023-10-17 08:25 UTC, Sebobo requested changes
Adjust the comment to be normal English again, then it's fine 👍

2023-10-17 08:25 UTC, Sebobo commented on Resources/Private/CodeTagPlugin/src/manifest.js
> +    // we duplicate editorOptions here so it would be possible to write smth like `$get('formatting.sup')`
Why make the comment less readable?

2023-10-17 08:28 UTC, mhsdesign commented on Resources/Private/CodeTagPlugin/src/manifest.js
> +    // we duplicate editorOptions here so it would be possible to write smth like `$get('formatting.sup')`
idk i copied the adjusted code from the neos ui 😂

2023-10-17 08:29 UTC, mhsdesign commented on Resources/Private/CodeTagPlugin/src/manifest.js
> +    // we duplicate editorOptions here so it would be possible to write smth like `$get('formatting.sup')`
could we please keep it like this so its only one commit and im lazy 😂

2023-10-17 08:54 UTC, Sebobo commented on Resources/Private/CodeTagPlugin/src/manifest.js
> +    // we duplicate editorOptions here so it would be possible to write smth like `$get('formatting.sup')`
Just do an amend?

2023-10-17 09:18 UTC, mhsdesign commented on Resources/Private/CodeTagPlugin/src/manifest.js
> +    // we duplicate editorOptions here so it would be possible to write smth like `$get('formatting.sup')`
i did it ^^

2023-10-17 09:22 UTC, Sebobo approved these changes

2023-10-17 09:22 UTC, merged